// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type User struct {
	ID           int32          `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	PasswordHash string         `json:"password_hash"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
