// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package sqlc

import (
	"context"
	"database/sql"
)

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(
    SELECT 1 FROM profiles
    WHERE username = $1
) AS exists
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    user_id,
    username,
    display_name,
    bio,
    website
) VALUES ($1, $2, $3, $4, $5)
    RETURNING id, user_id, username, display_name, bio, website, created_at, updated_at
`

type CreateProfileParams struct {
	UserID      int32          `json:"user_id"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	Bio         sql.NullString `json:"bio"`
	Website     sql.NullString `json:"website"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.UserID,
		arg.Username,
		arg.DisplayName,
		arg.Bio,
		arg.Website,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
WHERE user_id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, userID)
	return err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, username, display_name, bio, website, created_at, updated_at FROM profiles
WHERE user_id = $1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID int32) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUsername = `-- name: GetProfileByUsername :one
SELECT id, user_id, username, display_name, bio, website, created_at, updated_at FROM profiles
WHERE username = $1
`

func (q *Queries) GetProfileByUsername(ctx context.Context, username string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUsername, username)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, user_id, username, display_name, bio, website, created_at, updated_at FROM profiles
ORDER BY created_at DESC
    LIMIT $1 OFFSET $2
`

type ListProfilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProfiles(ctx context.Context, arg ListProfilesParams) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.Bio,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProfilesByUsername = `-- name: SearchProfilesByUsername :many
SELECT id, user_id, username, display_name, bio, website, created_at, updated_at FROM profiles
WHERE username ILIKE $1
ORDER BY username
    LIMIT $2 OFFSET $3
`

type SearchProfilesByUsernameParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) SearchProfilesByUsername(ctx context.Context, arg SearchProfilesByUsernameParams) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, searchProfilesByUsername, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.Bio,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    username = $2,
    display_name = $3,
    bio = $4,
    website = $5,
    updated_at = NOW()
WHERE user_id = $1
    RETURNING id, user_id, username, display_name, bio, website, created_at, updated_at
`

type UpdateProfileParams struct {
	UserID      int32          `json:"user_id"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	Bio         sql.NullString `json:"bio"`
	Website     sql.NullString `json:"website"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.UserID,
		arg.Username,
		arg.DisplayName,
		arg.Bio,
		arg.Website,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE profiles
SET
    username = $2,
    updated_at = NOW()
WHERE user_id = $1
    RETURNING id, user_id, username, display_name, bio, website, created_at, updated_at
`

type UpdateUsernameParams struct {
	UserID   int32  `json:"user_id"`
	Username string `json:"username"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateUsername, arg.UserID, arg.Username)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
