// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    user_id,
    provider,
    ip_address,
    user_agent,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING id, user_id, provider, ip_address, user_agent, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID        string         `json:"id"`
	UserID    int32          `json:"user_id"`
	Provider  sql.NullString `json:"provider"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT s.id, s.user_id, s.provider, s.ip_address, s.user_agent, s.expires_at, s.created_at, s.updated_at, u.id, u.username, u.email, u.password_hash, u.avatar_url, u.provider, u.provider_user_id, u.access_token, u.refresh_token, u.expires_at, u.name, u.first_name, u.last_name, u.nick_name, u.description, u.location, u.created_at, u.updated_at
FROM sessions s
         JOIN users u ON s.user_id = u.id
WHERE s.id = $1 AND s.expires_at > NOW()
`

type GetSessionByIDRow struct {
	ID             string         `json:"id"`
	UserID         int32          `json:"user_id"`
	Provider       sql.NullString `json:"provider"`
	IpAddress      sql.NullString `json:"ip_address"`
	UserAgent      sql.NullString `json:"user_agent"`
	ExpiresAt      time.Time      `json:"expires_at"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	ID_2           int32          `json:"id_2"`
	Username       string         `json:"username"`
	Email          string         `json:"email"`
	PasswordHash   sql.NullString `json:"password_hash"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	Provider_2     sql.NullString `json:"provider_2"`
	ProviderUserID sql.NullString `json:"provider_user_id"`
	AccessToken    sql.NullString `json:"access_token"`
	RefreshToken   sql.NullString `json:"refresh_token"`
	ExpiresAt_2    sql.NullTime   `json:"expires_at_2"`
	Name           sql.NullString `json:"name"`
	FirstName      sql.NullString `json:"first_name"`
	LastName       sql.NullString `json:"last_name"`
	NickName       sql.NullString `json:"nick_name"`
	Description    sql.NullString `json:"description"`
	Location       sql.NullString `json:"location"`
	CreatedAt_2    sql.NullTime   `json:"created_at_2"`
	UpdatedAt_2    sql.NullTime   `json:"updated_at_2"`
}

func (q *Queries) GetSessionByID(ctx context.Context, id string) (GetSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Provider_2,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt_2,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.NickName,
		&i.Description,
		&i.Location,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, user_id, provider, ip_address, user_agent, expires_at, created_at, updated_at FROM sessions
WHERE user_id = $1 AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) GetUserSessions(ctx context.Context, userID int32) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
